import type { Metadata } from 'next';

import { Nav, NavigationItem, Footer } from '@shared';

const navigation: Array<NavigationItem> = [
  { name: 'Home', href: '/#banner', current: false },
  { name: 'Features', href: '/#features', current: false },
  { name: 'Recipes', href: '/recipes', current: false },
];
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Nav navigation={navigation} />
      <main>{children}</main>
      <Footer />
    </>
  );
}
